stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "./gradlew.bat clean build"
  artifacts:
    paths:
      - build/

deploy-spring:      # This job runs in the deploy stage, only on the main branch.
  stage: deploy
  environment: production
  only:
    - main  # Only run this job on the 'main' branch
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t ${CI_REGISTRY_IMAGE}/springboot:latest .
    - docker push ${CI_REGISTRY_IMAGE}/springboot:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/springboot:latest

deploy-job:      # This job runs in the deploy stage, only on the main branch.
  stage: deploy
  environment: production
  only:
    - main  # Only run this job on the 'main' branch
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/postgres:latest postgres/
    - docker push ${CI_REGISTRY_IMAGE}/postgres:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/postgres:latest
