
services:
  db:
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    container_name: vtrc-postgres
    restart: always
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

volumes:
  postgres: